# Introduction to NumPy
    hiya!

In [1]:
import numpy as np
np.__version__

'1.16.0'

### Differences between lists and NumPy Arrays
* An array's size is immutable.  You cannot append, insert or remove elements, like you can with a list.
* All of an array's elements must be of the same [data type](https://docs.scipy.org/doc/numpy-1.14.0/user/basics.types.html).
* A NumPy array behaves in a Pythonic fashion.  You can `len(my_array)` just like you would assume.
* Use ?np.array to get all info about np.array object
* GPA - Grade Point Average (Average of all your grade in all subjects on a scale from 1 to 4)

In [8]:
gpas_as_list = [4.0, 3.286, 3.5, 9.9, 1.1]
gpa = np.array(gpas_as_list)

In [13]:
len(gpa)

5

In [14]:
gpa.size

5

In [15]:
gpa.nbytes

40

In [20]:
students_gpas = np.array([
    [4.0, 3.286, 3.5, 1.1],
    [3.2, 3.8, 4.0, 4.0],
    [3.96, 3.92, 4.0, 4.0]
], np.float16)
students_gpas

array([[4.   , 3.285, 3.5  , 1.1  ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

In [24]:
students_gpas.ndim #number of dimensions

2

In [26]:
students_gpas.shape

(3, 4)

In [28]:
students_gpas.size

12

In [30]:
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7fea8b3cc830
byteorder:  little
byteswap:  False
type: float16


In [35]:
students_gpas[0][3]

1.1

## About data types

* By choosing the proper [data type](https://docs.scipy.org/doc/numpy-1.14.0/user/basics.types.html) you can greatly reduce the size required to store objects
* Data types are maintained by wrapping values in a [scalar representation](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.scalars.html)
* `np.zeros` is a handy way to create an empty array filled with zeros.

In [2]:
study_minutes = np.zeros(100,np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [3]:
%whos

Variable        Type       Data/Info
------------------------------------
np              module     <module 'numpy' from '/Li<...>kages/numpy/__init__.py'>
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [4]:
study_minutes[0] = 150
first_day_minutes = study_minutes[0]

first_day_minutes

150

In [5]:
type(first_day_minutes)

numpy.uint16

In [6]:
study_minutes[1] = 60
study_minutes[2:6] = [80, 60, 30, 90]
study_minutes

array([150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)